swarmauri/swarmakit

libs/vue/src/components/BatteryLevelIndicator/BatteryLevelIndicator.vue, libs/vue/src/components/BottomNavigationBar/BottomNavigationBar.vue, libs/vue/src/components/BreadcrumbWithDropdowns/BreadcrumbWithDropdowns.vue, libs/vue/src/components/BrushTool/BrushTool.stories.ts, libs/vue/src/components/CalendarView/CalendarView.stories.ts, libs/vue/src/components/CalendarView/CalendarView.vue, libs/vue/src/components/Canvas/Canvas.stories.ts, libs/vue/src/components/Captcha/Captcha.stories.ts, libs/vue/src/components/Captcha/Captcha.vue, libs/vue/src/components/CardActions/CardActions.stories.ts, libs/vue/src/components/CardBadge/CardBadge.stories.ts, libs/vue/src/components/CardBody/CardBody.stories.ts, libs/vue/src/components/CardFooter/CardFooter.stories.ts, libs/vue/src/components/CardHeader/CardHeader.stories.ts
=> Fix(CardHeader.stories.ts): Resolve the import and type errors in the CardHeader stories. 

libs/vue/src/components/BatteryLevelIndicator/BatteryLevelIndicator.vue, libs/vue/src/components/BottomNavigationBar/BottomNavigationBar.vue, libs/vue/src/components/BreadcrumbWithDropdowns/BreadcrumbWithDropdowns.vue, libs/vue/src/components/BrushTool/BrushTool.stories.ts, libs/vue/src/components/CalendarView/CalendarView.stories.ts, libs/vue/src/components/CalendarView/CalendarView.vue, libs/vue/src/components/Canvas/Canvas.stories.ts, libs/vue/src/components/Captcha/Captcha.stories.ts, libs/vue/src/components/Captcha/Captcha.vue, libs/vue/src/components/CardActions/CardActions.stories.ts, libs/vue/src/components/CardBadge/CardBadge.stories.ts
=> Fix(CardBadge.stories.ts): Resolve the import and type errors in the CardBadge stories.

libs/vue/src/components/BatteryLevelIndicator/BatteryLevelIndicator.vue, libs/vue/src/components/BottomNavigationBar/BottomNavigationBar.vue, libs/vue/src/components/BreadcrumbWithDropdowns/BreadcrumbWithDropdowns.vue
This PR resolves the TypeScript error TS2322 in the BreadcrumbWithDropdowns.vue component. 
The issue was caused by null being returned in the aria-current attribute, which is not assignable to the expected type. The fix replaces null with undefined, as per the correct type requirements.
=> Fix: Resolve TypeScript type error in BreadcrumbWithDropdowns component

libs/vue/src/components/BatteryLevelIndicator/BatteryLevelIndicator.vue, libs/vue/src/components/BottomNavigationBar/BottomNavigationBar.vue, libs/vue/src/components/BreadcrumbWithDropdowns/BreadcrumbWithDropdowns.vue, libs/vue/src/components/BrushTool/BrushTool.stories.ts
Replaced the `Story` import with `StoryFn` as that's the correct module to imported. 
This fix also resolves the `args` type error  as the `StoryFn` correctly uses the components types.
=> Fix(BrushTool): This fix resolves the import and Type errors in the BrushTool stories

libs/vue/src/components/BatteryLevelIndicator/BatteryLevelIndicator.vue, libs/vue/src/components/BottomNavigationBar/BottomNavigationBar.vue, libs/vue/src/components/BreadcrumbWithDropdowns/BreadcrumbWithDropdowns.vue, libs/vue/src/components/BrushTool/BrushTool.stories.ts, libs/vue/src/components/CalendarView/CalendarView.stories.ts, libs/vue/src/components/CalendarView/CalendarView.vue
This fix resolves the mentioned errors by replacing the `Story` import with the correct module which is `StoryFn`. 
The import fix also resolves the type error on `args` as `StoryFn` correctly fetches the components props. 
Due to the `CalendarView` component not having props declared, there was still a type error on the `args` argument. To fix this I declared props for the component.
=> Fix(CalendarView): Resolve the import and type errors in the CalendarView stories.

libs/vue/src/components/BatteryLevelIndicator/BatteryLevelIndicator.vue, libs/vue/src/components/BottomNavigationBar/BottomNavigationBar.vue, libs/vue/src/components/BreadcrumbWithDropdowns/BreadcrumbWithDropdowns.vue, libs/vue/src/components/BrushTool/BrushTool.stories.ts, libs/vue/src/components/CalendarView/CalendarView.stories.ts, libs/vue/src/components/CalendarView/CalendarView.vue, libs/vue/src/components/Canvas/Canvas.stories.ts, libs/vue/src/components/Captcha/Captcha.stories.ts, libs/vue/src/components/Captcha/Captcha.vue, libs/vue/src/components/CardActions/CardActions.stories.ts, libs/vue/src/components/CardBadge/CardBadge.stories.ts, libs/vue/src/components/CardBody/CardBody.stories.ts
=> Fix(CardBody.stories.ts): Resolve the import and type errors in the CardBody stories.

libs/vue/src/components/CardbasedList/CardbasedList.vue
Passed the `props`  of the component to the setup in order to access the cards array.
=> fix(CardbasedList.vue): Resolve cannot find name error:

libs/vue/src/components/CardbasedList/CardbasedList.vue, libs/vue/src/components/Carousel/Carousel.stories.ts, libs/vue/src/components/Carousel/Carousel.vue
Replaced the null value on the Carousel stories file to resolve the type error as the `interval` does not take a null type.
Updated the aria-hidden attribute to use a boolean expression instead of a string, resolving the Carousel Component TypeScript type error. This ensures proper accessibility behavior for the carousel items.
=> Fix(Carousel): Resolve Type errors for both the Carousel component and stories files. 

libs/vue/src/components/CheckList/CheckList.vue
Removed the unused 'PropType' import from the CheckList component to resolve the TS6133 error. This change cleans up the code and ensures no unnecessary imports remain in the project.
=> fix(CheckList.vue): Remove unused `ref` import.

libs/vue/src/components/Checkbox/Checkbox.stories.ts, libs/vue/src/components/Checkbox/Checkbox.vue
Updated the Checkbox storybook file to include `Meta` and `StoryFn` types from `@storybook/vue3`. This resolves TypeScript errors and ensures proper type-checking for Storybook components.
- Cast event target to HTMLInputElement to access 'checked' property
- Ensure aria-checked and aria-disabled attributes are correctly bound
=> Fix(Checkbox): Fix TypeScript errors for the Storybook and Component files.

libs/vue/src/components/ColorPicker/ColorPicker.stories.ts
Replaced the `Story` import from storybook with `StoryFn` as thats the required module.
This fix also resolves the type error for `args` as `StoryFn` uses the components types.
=> fix(ColorPicker.stories.ts): Resolve TypeScript errors in the Color Picker Story File

libs/vue/src/components/ContextualNavigation/ContextualNavigation.stories.ts, libs/vue/src/components/ContextualNavigation/ContextualNavigation.vue
fix(ContextualNavigation.vue): Resolve TypeScript error at the aria-expanded attribute.
Beta: Correctly bound the aria-expanded attribute to the `isVisible` value.
fix(ContextualNavigation.stories.ts): Resolve TypeScript error for the button.click() method: Cast the button element to its correct HTML type which is `HTMLButtonElement`. This makes it possible for the button to access the click method.
=> fix(ContextualNavigation): Resolve TypeScript errors on the Storybook and Component files

libs/vue/src/components/DataFilterPanel/DataFilterPanel.stories.ts
=> fix(DataFilterPanel.stories.ts): Resolve TypeScript type errors in DataFilterPanel StoryBook

libs/vue/src/components/DataGrid/DataGrid.stories.ts
- Commented out the `argTypes` in the DataGrid story to resolve type compatibility issues with TypeScript.
- Removed the explicit type declaration for `Meta`, allowing for more flexible type inference and avoiding strict type checks that were causing errors.
- This change simplifies the configuration and prevents type mismatches, ensuring the Storybook stories function correctly without type errors.
=> fix(Datagrid.stories.ts):  TypeScript Error in Storybook Configuration

libs/vue/src/components/DataImportDialog/DataImportDialog.stories.ts
=> fix(DataImportDialog.stories.ts): Resolve TypeScript type errors in DataImportDialog storybook file.

libs/vue/src/components/DataSummary/DataSummary.stories.ts
=> fix(DataSummary.stories.ts): Resolve TypeScript errors in DataSummary storybook file.

libs/vue/src/components/DataTable/DataTable.stories.ts, libs/vue/src/components/DataTable/DataTable.vue
1. Component file (DataTable.vue) - There were key errors in this file: An unused variable error that occured due to the `columnKey` being declared but never used.
Solution: I resolved this by just logging the column key.
2. Storybook file (Datatable.stories.ts) - TypeScript errors in the DataTable.stories.ts file were resolved by introducing Meta and StoryFn types from @storybook/vue3. This ensures that the Storybook configuration follows proper TypeScript conventions.
=> Fix: Resolve TypeScript type errors on both the component and storybook files.

libs/vue/src/components/DateAndTimePicker/DateAndTimePicker.stories.ts, libs/vue/src/components/DateAndTimePicker/DateAndTimePicker.vue
Resolved type errors in the component file by correctly binding the `disabled` value to the `aria-disabled` attribute. It was passed a string instead of a boolean.
=> fix(DateAndTimePicker): Resolve TypeScript type errors in both the component and storybook files.

libs/vue/src/components/DatePicker/DatePicker.stories.ts, libs/vue/src/components/DatePicker/DatePicker.vue
Resolved type errors in the component file by correctly binding the disabled value to the aria-disabled attribute. It was passed a string instead of a boolean.
TypeScript errors in the DatePicker.stories.ts file were resolved by introducing Meta and StoryFn types from @storybook/vue3. This ensures that the Storybook configuration follows proper TypeScript conventions.
=> fix(DatePicker): Resolve TypeScript type errors in both the component and storybook files.

libs/vue/src/components/DeckOfCards/DeckOfCards.stories.ts, libs/vue/src/components/DeckOfCards/DeckOfCards.vue
- TypeScript errors in the DeckofCards.stories.ts file were resolved by introducing Meta and StoryFn types from @storybook/vue3. This ensures that the Storybook configuration follows proper TypeScript conventions.
- Updated the onDrop method to use props.cards instead of cards.value.
=> fix(DeckofCards): Resolve TypeScript type errors. Resolve `cannot find name 'cards'` error: 

libs/vue/src/components/DragAndDropScheduler/DragAndDropScheduler.vue
- Added 'events' prop to DragAndDropScheduler.vue to resolve TypeScript error.
- Updated prop type to accept an array of event objects.
- Ensured default value is set for the events prop.
=> Fix: Define 'events' prop in DragAndDropScheduler component

libs/vue/src/components/DropdownMenu/DropdownMenu.stories.ts
- Resolved by casting the button element to a `HTMLElement` as the click method is not defined in `Element`
=> fix(DropDownMenu.stories.ts): Resolve the click method was not found error.

libs/vue/src/components/EmbeddedMediaIframe/EmbeddedMediaIframe.vue
Correctly bind `isBuffering` value to the `aria-busy` attribute.
=> fix(EmbeddedMediaIframe.vue): Resolve TypeScript type error on aria attribute.

libs/vue/src/components/EmojiReactionPoll/EmojiReactionPoll.stories.ts
- Removed argTypes from EmojiReactionPoll stories to allow Meta to handle prop types automatically.
- Fixed incorrect import of StoryFn module to ensure proper functionality.
=> fix:(EmojiReactionPoll): Simplify Storybook configuration and correct StoryFn import

libs/vue/src/components/EventDetailsDialog/EventDetailsDialog.vue
- Deleted an the `ref` import that was causing a compilation error, improving code cleanliness and preventing unnecessary warnings.
=> fix: Remove unused import to resolve compilation error

libs/vue/src/components/FavoritesList/FavoritesList.stories.ts
- Used the correct control type for the items argument to resolve the type error.
=> fix(FavoritesList.stories) : Resolve TypeScript type error for wrong control type used.

libs/vue/src/components/FieldEditableDataTable/FieldEditableDataTable.stories.ts, libs/vue/src/components/FieldEditableDataTable/FieldEditableDataTable.vue
fix(FieldEditableDataTable.vue): Fix type error in editField argument by converting key to string
fix(FieldEditableDataTable.stories.ts) :Resolved type errors by introducing the Meta and StoryFn modules for better type handling.
=> fix(FieldEditableDataTable): Resolve TypeScript type errors.

libs/vue/src/components/FileInputWithPreview/FileInputWithPreview.stories.ts, libs/vue/src/components/FileInputWithPreview/FileInputWithPreview.vue
fix(FileInputWithPreview.stories.ts): Resolve TypeScript type errors : Introduce Meta and StoryFn modules for proper type handling
fix(FileInputWithPreview.vue): Resolve TypeScipt type error: Correctly bind the aria-disabled attribute to the correct value type of disabled.
=> fix(FileInputWithPreview): Resolve TypeScript type errors and incorrect value binding to aria attribute.

libs/vue/src/components/GroupedList/GroupedList.stories.ts
fix(GroupedList.stories.ts): remove unused 'args' parameter from GroupExpanded.play function
fix(GroupedList.stories.ts): Resolve method not found error : - Resolve the error by casting the clicked elements to a HTMLElement.
=> Fix (GroupedList): Resolve unused variables and cast elements to the correct type. 

libs/vue/src/components/FlipCard/FlipCard.stories.ts, libs/vue/src/components/FloatingActionButton/FloatingActionButton.vue
- The Floating Button storybook is  accessing isExpanded prop which is not present as a prop in the vue file. Introducing the prop to the component resolved this error.
=> fix(FloatinActionButton.stories.tsx): Resolve TypeScript type error by adding prop in component file.

libs/vue/src/components/ImageChoicePoll/ImageChoicePoll.stories.ts
- `InitialValue` only takes number and undefined as values. Resolved by changing the value to undefined from null.
=> fix(ImageChoicePoll.stories.ts): Resolve TypeScript error.

libs/vue/src/components/ImageSlider/ImageSlider.stories.ts, libs/vue/src/components/ImageSlider/ImageSlider.vue
fix(ImageSlider.vue): Resolve variable not used error :  Remove the `computed` import from vue as it is not used.
fix(ImageSlider.stories.ts): Resolve type error for the array control : Replace the array control with object for the images as it is not supported by StoryBook.
=> Fix(ImageSlider) : Resolve variable not used Errors and also TypeScript type Error

libs/vue/src/components/MultiselectList/MultiselectList.stories.ts, libs/vue/src/components/MultiselectList/MultiselectList.vue
- Resolve the unused variable by removing the index variable on the li element as it was not used.
- Added null checks for the item element to resolve the items might be null error.
- Cast the item element as a HTMLELement to access the click method
- Remove the args argument passed on the play function to resolve the variable is not read error.
=> Multi select list

libs/vue/src/components/NumberedList/NumberedList.stories.ts, libs/vue/src/components/NumberedList/NumberedList.vue
- Remove the arg argument passed on the play function to resolve the variable not used error.
-Add null checks for the item element
- Cast the item as a HTMLElement to access the click method.
- Remove unused index argument to resolve variable not read error.
=> Numbered list

libs/vue/src/components/PinnedList/PinnedList.stories.ts, libs/vue/src/components/PinnedList/PinnedList.vue
fix(PinnedList.vue): Remove the computed and props declarations as they were not used.
fix(PinnedList.stories.ts): Resolve the variable not used and null check errors - Introduce null check for the item element.
- Remove the arg argument passed to the hover.play function as it was not used.
=> Pinned list

libs/vue/src/components/PokerTimer/PokerTimer.vue
Changed the type of intervalId from number to ReturnType<typeof setInterval> to resolve TypeScript error regarding type assignment. This ensures compatibility with the return value of setInterval.
=> fix(PokerTimer.vue): update intervalId type to ReturnType<typeof setInterval>

libs/vue/src/components/Pagination/Pagination.stories.ts
- Add a null check for the `item` html element.
- Remove the args argument passed to the play function as it was not used.
=> fix(Pagination.stories.ts): Resolve variable not used and null error.

libs/vue/package.json, libs/vue/src/components/RichTextEditor/RichTextEditor.stories.ts
fix(RichTextEditor.stories.ts): Resolve TypeScript Type errors. - Introduce Meta and StoryFn modules for proper type handling.
=>  fix(RichTextEditor.vue):Install type definitions for Quill to resolve module not found error Beta

libs/vue/src/components/ScrollableList/ScrollableList.stories.ts
- Add a null check for the `item` variable to resolve null check error.
- Remove args argument passed to the hover.play function as it was not being used.
=> fix:(ScrollableList.stories.ts): Resolve null check and unused variable error.

libs/vue/src/components/LiveStreamPlayer/LiveStreamPlayer.vue
- Return the unused variables from setup in order for them to be accessible in the template.
=> fix(LiveStreamPlayer.vue): Resolve TypeScript type and unused variables errors.

libs/vue/src/components/LiveStreamPlayer/LiveStreamPlayer.vue, libs/vue/src/components/LoadMoreButtonInList/LoadMoreButtonInList.stories.ts, libs/vue/src/components/LoadMoreButtonInList/LoadMoreButtonInList.vue
fix(LoadMoreButtonInList.vue): Resolve TypeScript Type error:
- Correctly bind `isLoading` value to the aria-busy attribute.
fix(LoadMoreButtonInList.stories.ts): Resolve unused variable and method not found errors.
- Remove the args argument passed to the play function as it is not used
- Cast the button as a HTMLElement to access the click() method.
=> fix(LoadMoreButtonInList.vue): Resolve TypeScript Type error:

libs/vue/src/components/SingleChoicePoll/SingleChoicePoll.vue
- Correctly bind value to aria-checked aria attribute
- Remove the props argument as it is not used.
=> fix(SingleChoicePoll): Resolve TypeScript type and unused variable error.

libs/vue/src/components/SearchBar/SearchBar.vue
- Changed the handleFocus and handleBlur methods to modify a local reactive variable instead of directly assigning to the read-only prop `isFocused`.
=> Fix:(SearchBar.vue) Update SearchBar component to use local reactive variable for focus state

libs/vue/src/components/ToggleSwitch/ToggleSwitch.stories.ts, libs/vue/src/components/ToggleSwitch/ToggleSwitch.vue
fix(ToggleSwitch.vue): Properly bind attribute to value - Properly bind aria-checked attribute to the checked value.
=> fix(ToggleSwitch.stories.ts): Resolve TypeScript type errors by introducing the Meta and StoryFn modules for proper type handling.

libs/vue/src/components/VisualCueForAccessibilityFocusIndicator/VisualCueForAccessibilityFocusIndicator.vue
Resolved the error "isFocused cannot be changed as it is read-only" by correctly updating the isFocused state using isFocused.value instead of directly assigning to isFocused. This ensures proper reactivity in the component.
=> Fix: Update isFocused handling in setup to use ref.value

libs/vue/src/components/WinningHandDisplay/WinningHandDisplay.stories.ts
Changed the control type for winningCards from 'array' to 'object' to ensure compatibility with the expected type in the Storybook configuration.
=> fix: update winningCards, PlayerCards,CommunityCards control type to 'object' in WinningHandDisplay stories

README.md
- Replaced the previous link which lead to the `swarmauri-sdk` contributing documentation with the swarmakit documentation.
=> fix(README.md): Fix the contributing documentation link.

libs/vue/src/components/360-DegreeImageViewer/360-DegreeImageViewer.stories.ts
The default export was casted as unkown which produced and error when trying to access the storybook.
Removed the unkown cast and fixed the image control type from array to object.
=> fix(360-DegreeImageViewer.stories.ts): Resolve esport default storybook error.

libs/sveltekit/src/components/Accordion/Accordion.stories.ts, libs/sveltekit/src/components/Accordion/Accordion.svelte
fix: Resolve TypeScript error for Accordion component props
- Updated the Accordion story file to correctly import the Accordion component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, the Accordion component can now be used in Storybook without type errors, and the props can be controlled as intended.
fix: Remove tabindex from accordion content div to improve accessibility
The tabindex attribute was removed from the accordion content div to …
=> Accordion - SvelteKit

libs/sveltekit/src/components/360-DegreeImageViewer/360-DegreeImageViewer.stories.ts, libs/sveltekit/src/components/360-DegreeImageViewer/360-DegreeImageViewer.svelte
fix(360-DegreeImageViewer.stories.ts): Fix StoryFn import error.
Correctly import the StoryFn module from storybook/svelte.
fix(360-DegreeImageViewr.svelte): Fix type error and non-interactive elements errors.
- Set the interval's variable type to the correct return type which is setInterval
- Set the main div's role to button to resolve the non-interactive elements cannot be passed interactivity error.
=> 360-DegreeImageViewe - SvelteKit

libs/sveltekit/src/components/ActivityIndicators/ActivityIndicators.stories.ts
- Updated the ActivityIndicators story file to correctly import the Accordion component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, the ActivityIndicators component can now be used in Storybook without type errors, and the props can be controlled as intended.
=> fix(ActivityIndicators.stories.ts): Resolve TypeScript error for ActivityIndicators.stories.ts args  props

libs/sveltekit/src/components/AudioPlayerAdvanced/AudioPlayerAdvanced.stories.ts, libs/sveltekit/src/components/AudioPlayerAdvanced/AudioPlayerAdvanced.svelte
fix(AudioPlayerAdvanced.stories.ts): Resolve StoryFn correct module import.
fix: resolve audio duration initialization issue in AudioPlayerAdvanced
- Add dedicated duration state variable to handle audio length
- Implement loadedmetadata event listener to properly initialize duration
- Move duration access from template to controlled state variable
This fixes the undefined duration error that occurred when trying to access
audioElement.duration before the audio metadata was fully loaded. The solution
ensures the seek control's max value is properly set only after the audio
file's metadata is available.
Technical changes:
- Added duration: number = 0 state variable
- Added loadedmetadata event listener in onMount
- Updated seek control input to use duration variable instead of direct …
=> AudioPlayerAdvanced - SvelteKit

libs/sveltekit/src/components/AudioWaveformDisplay/AudioWaveformDisplay.stories.ts, libs/sveltekit/src/components/AudioWaveformDisplay/AudioWaveformDisplay.svelte
fix(AudioWaveformDisplay.stories.ts): Resolve StoryFn correct module import.
fix(AudioWaveformDisplay.svelte): Resolve unused variable error by exporting it as a constant as it is used externaly.
=> AudioWaveformDisplay- SvelteKit

libs/sveltekit/src/components/Badge/Badge.stories.ts
fix(Badge.stories.ts): Resolve TypeScript error for Badge.stories.ts args props
- Updated the Badge story file to correctly import the Badge component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, the Badge component can now be used in Storybook without type errors, and the props can be controlled as intended.
=> Badge - Svelte

libs/sveltekit/src/components/Button/Button.stories.ts
- Updated the Button story file to correctly import the Button component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, the Button component can now be used in Storybook without type errors, and the props can be controlled as intended.
=> fix(Button.stories.ts): Resolve TypeScript error for Button.stories.ts args  props

libs/sveltekit/src/components/BatteryLevelIndicator/BatteryLevelIndicator.stories.ts
- Updated the BatteryLevelIndicator story file to correctly import the BatteryLevelIndicator component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, the BatteryLevelIndicator component can now be used in Storybook without type errors, and the props can be controlled as intended.
=> fix(BatteryLevelIndicator.stories.ts): Resolve TypeScript error for BatteryLevelIndicator.stories.ts args  props

libs/sveltekit/src/components/BadgeWithCounts/BadgeWithCounts.stories.ts
fix(BadgeWithCounts.stories.ts): Resolve TypeScript error for BadgeWithCounts.stories.ts args  props
- Updated the BadgeWithCounts story file to correctly import the BadgeWithCounts component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, the BadgeWithCounts component can now be used in Storybook without type errors, and the props can be controlled as intended.
fix(BadgeWithCounts.stories.ts): Remove unused variable declaration and import.
=> BadgeWithCounts - SvelteKit

libs/sveltekit/src/components/Captcha/Captcha.stories.ts
fix(Captcha.stories.ts): Resolve TypeScript error for Captcha.storiests args  props
- Updated the Captcha story file to correctly import the Captcha component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, the Captcha component can now be used in Storybook without type errors, and the props can be controlled as intended.
=> Captcha - SvelteKit

libs/sveltekit/src/components/CardbasedList/CardbasedList.stories.ts, libs/sveltekit/src/components/CardbasedList/CardbasedList.svelte
fix(CardbasedList.stories.ts): Resolve TypeScript error for CardbasedList.stories.ts args  props
- Updated the CardBasedList story file to correctly import the CardBasedList component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, the CardBasedList component can now be used in Storybook without type errors, and the props can be controlled as intended.
fix(CardbasedList.svelte): enhance accessibility of card elements
- Changed <div> to have …
=> CardBasedList-SvelteKit

libs/sveltekit/src/components/Carousel/Carousel.stories.ts, libs/sveltekit/src/components/Carousel/Carousel.svelte
fix(Carousel.stories.ts): Resolve incorrect import for the StoryFn module.
- Correctly Import the StoryFn from '@storybook/svelte'.
- Pass the correct control type for the images props which is object according to Storybook.
fix(Carousel.svelte): Resolve 'Cannot find name get' error in Carousel component
- Added the missing import for the `get` function from `svelte/store` in the Carousel.svelte file.
- This change ensures that the `get` function can be used to retrieve the current value of the `isHovered` writable store, preventing runtime errors during the autoplay functionality.
- The fix enhances the stability of the carousel component, particularly when the autoplay feature is enabled.
=> Carousel-SvelteKit

libs/sveltekit/src/components/Checkbox/Checkbox.stories.ts
fix(Checkbox.stories.ts): Resolve TypeScript error for Checkbox.stories.ts args  props
- Updated the Checkbox story file to correctly import the Checkbox component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, the Checkbox component can now be used in Storybook without type errors, and the props can be controlled as intended.
=> Checkbox-SvelteKit

libs/sveltekit/src/components/CheckList/CheckList.stories.ts, libs/sveltekit/src/components/CheckList/CheckList.svelte
fix(CheckList.stories.ts): Resolve TypeScript error for CheckList.stories.ts args  props
- Updated the CheckList story file to correctly import the CheckList component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, the CheckList component can now be used in Storybook without type errors, and the props can be controlled as intended.
fix(CheckList.svelte): Fix accessibility issue by associating labels with checkboxes in CheckList component.
=> Checklist-SvelteKit

libs/sveltekit/src/components/CheckList/CheckList.stories.ts, libs/sveltekit/src/components/CheckList/CheckList.svelte, libs/sveltekit/src/components/CollapsibleMenuList/CollapsibleMenuList.stories.ts, libs/sveltekit/src/components/CollapsibleMenuList/CollapsibleMenuList.svelte
fix(CollapsibleMenuList.stories.ts): Resolve TypeScript error for CollapsibleMenuList.stories.ts args  props
- Updated the CollapsibleMenuList story file to correctly import the CollapsibleMenuList component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, the CollapsibleMenuList component can now be used in Storybook without type errors, and the props can be controlled as intended.
fix(CollapsibleMenuList.svelte): Fix accessibility warning by …
=> CollapsibleMenu-SvelteKit

libs/sveltekit/src/components/ColorPicker/ColorPicker.stories.ts
fix(ColorPicker.stories.ts): Resolve TypeScript error for ColorPicker stories.ts args  props
- Updated the ColorPicker story file to correctly import the ColorPicker component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, the ColorPicker component can now be used in Storybook without type errors, and the props can be controlled as intended.
=> ColorPicker-SvelteKit

libs/sveltekit/src/components/ContextualList/ContextualList.stories.ts
fix(ContextualList.stories.ts): Resolve TypeScript error for ContextualList.stories.ts args  props
- Updated the ContextualList story file to correctly import the ContextualList component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, the ContextualList component can now be used in Storybook without type errors, and the props can be controlled as intended.
=> ContextualList-SvelteKit

libs/sveltekit/src/components/CountdownTimer/CountdownTimer.stories.ts, libs/sveltekit/src/components/CountdownTimer/CountdownTimer.svelte
fix(CountdownTimer.stories.ts): Resolve TypeScript error for CountdownTimer.stories.ts args  props
- Updated the CountdownTimer story file to correctly import the CountdownTimer component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, CountdownTimer component can now be used in Storybook without type errors, and the props can be controlled as intended.
Fix(CountdownTimer.svelte): Resolve TypeScript error by using non-null assertion for …
=> CountdownTimer-SvelteKit

libs/sveltekit/src/components/DataGrid/DataGrid.stories.ts
fix(DataGrid.stories.ts): Resolve TypeScript error for DataGrid.stories.ts args  props
- Updated the DataGrid story file to correctly import the DataGrid component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, DataGrid component can now be used in Storybook without type errors, and the props can be controlled as intended.
=> DataGrid-SvelteKit

libs/sveltekit/src/components/DateAndTimePicker/DateAndTimePicker.stories.ts
fix(DateAndTimePicker.stories.ts): Resolve TypeScript error for DateAndTimePicker.stories.ts args  props
- Updated the DateAndTimePicker story file to correctly import the DateAndTimePicker component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, DateAndTimePicker component can now be used in Storybook without type errors, and the props can be controlled as intended.
=> DateAndTimePicker - SvelteKit

libs/sveltekit/src/components/DatePicker/DatePicker.stories.ts
fix(DatePicker.stories.ts): Resolve TypeScript error for DatePicker.stories.ts args  props
- Updated the DatePicker story file to correctly import the DatePicker component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, DatePicker component can now be used in Storybook without type errors, and the props can be controlled as intended.
=> DatePicker-SvelteKit

libs/sveltekit/src/components/DragAndDropFileArea/DragAndDropFileArea.stories.ts, libs/sveltekit/src/components/DragAndDropFileArea/DragAndDropFileArea.svelte
fix(DragAndDropFileArea.svelte): update file upload area role from region to group
- Replace role="region" with role="group" to resolve ARIA validation error
- Maintain aria-disabled attribute functionality
- Improve semantic meaning of the file upload container
fix(DragAndDropFileArea.stories.ts): Resolve TypeScript error for DragAndDropFileArea.stories.ts args props
- Updated the DragAndDropFileArea story file to correctly import the DragAndDropFileArea component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
- This change addresses the TypeScript error: "Object literal may only specify known properties, and 'isOpen' does not exist in type 'Partial<ComponentAnnotations<...>>'" by ensuring that the props are correctly defined …
=> DragAndDropFileArea-SvelteKit

libs/sveltekit/src/components/EmbeddedMediaIframe/EmbeddedMediaIframe.stories.ts
fix(EmbeddedMediaIframe.stories.ts): Resolve incorrect import for the StoryFn module from StoryBook.
=> EmbeddedMediaIframe-SvelteKit

libs/sveltekit/src/components/ExpandableList/ExpandableList.stories.ts, libs/sveltekit/src/components/ExpandableList/ExpandableList.svelte, libs/sveltekit/src/components/FavoritesList/FavoritesList.stories.ts, libs/sveltekit/src/components/FavoritesList/FavoritesList.svelte, libs/sveltekit/src/components/FileUpload/FileUpload.stories.ts, libs/sveltekit/src/components/FileUpload/FileUpload.svelte
fix(FileUpload.svelte): Provide an aria-role attribute to the file upload div to resolve accessibilty warnings.
fix(FileUpload.stories.ts): Resolve TypeScript error for FileUpload.stories.ts args props
- Updated the FileUpload story file to correctly import the FileUpload component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, FileUpload component can now be used in Storybook without type errors, and the props can be controlled as intended.
=> FileUpload-SvelteKit

libs/sveltekit/src/components/FilterableList/FilterableList.stories.ts, libs/sveltekit/src/components/FilterableList/FilterableList.svelte
fix(FilterableList.svelte): Add unused css class to the no results list to resolve css warning.
fix(FilterableList.stories.ts): Resolve TypeScript error for FilterableList.stories.ts args props
- Updated the FilterableList story file to correctly import the FilterableList component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, FilterableList component can now be used in Storybook without type errors, and the props can be controlled as …
=> FilterableList-SvelteKit

libs/sveltekit/src/components/GroupedList/GroupedList.stories.ts, libs/sveltekit/src/components/GroupedList/GroupedList.svelte
fix(GroupedList.stories.ts): Resolve TypeScript error for GroupedList.stories.ts args props
- Updated the GroupedList story file to correctly import the GroupedList component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, GroupedList component can now be used in Storybook without type errors, and the props can be controlled as intended.
fix(GroupedList.svelte): Add keyboard event handler to selected-item for accessibility.
- Added on:keydown …
=> GroupedList-SvelteKit

libs/sveltekit/src/components/IconButton/IconButton.stories.ts
fix(IconButton.stories.ts): Resolve TypeScript error for IconButton.stories.ts args props
- Updated the IconButton story file to correctly import the IconButton component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, IconButton component can now be used in Storybook without type errors, and the props can be controlled as intended.
=> IconButton-SvelteKit

libs/sveltekit/src/components/ImageSlider/ImageSlider.stories.ts, libs/sveltekit/src/components/ImageSlider/ImageSlider.svelte
fix(ImageSlider.stories.ts): Fix incorrect import module for the StoryFn module.
fix(ImageSlider.svelte): Change the image-slider role to menu to accommodate events.
=> ImageSlider-SvelteKit

libs/sveltekit/src/components/InteractivePollResults/InteractivePollResults.stories.ts, libs/sveltekit/src/components/InteractivePollResults/InteractivePollResults.svelte
fix(InteractivePollResults.stories.ts): Resolve TypeScript error for InteractivePollResults.stories.ts args props
- Updated the InteractivePollResults story file to correctly import the InteractivePollResults component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, InteractivePollResults component can now be used in Storybook without type errors, and the props can be controlled as intended.
fix(InteractivePollResults.svelte): Remove the export …
=> InteractivePollResults-SvelteKit

libs/sveltekit/src/components/LoadingBarsWithSteps/LoadingBarsWithSteps.stories.ts, libs/sveltekit/src/components/LoadingBarsWithSteps/LoadingBarsWithSteps.svelte
fix(LoadingBarsWithSteps.svelte): Remove the export keyword from the type declaration Step as it was accessed internally by steps variable.
fix(LoadingBarsWithSteps.stories.ts): Resolve TypeScript error for LoadingBarsWithSteps.stories.ts args props
- Updated the LoadingBarsWIthSteps story file to correctly import the LoadingBarsWithSteps component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, LoadingBarsWithSteps component can now be used in …
=> LoadingBarsWithSteps-SvelteKit

libs/sveltekit/src/components/LoadingSpinner/LoadingSpinner.stories.ts
fix(LoadingSpinner.stories.ts): Resolve TypeScript error for LoadingSpinner.stories.ts args props
- Updated the LoadingSpinner story file to correctly import the LoadingSpinner component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, LoadingSpinner component can now be used in Storybook without type errors, and the props can be controlled as intended.
=> LoadingSpinner-SvelteKit

libs/sveltekit/src/components/LoadmorebuttoninList/LoadmorebuttoninList.stories.ts
fix(LoadmorebuttoninList.stories.ts): Resolve TypeScript error for LoadmorebuttoninList.stories.ts args props
- Updated the LoadmorebuttoninList story file to correctly import the LoadmorebuttonInList component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, LoadmorebuttoninList component can now be used in Storybook without type errors, and the props can be controlled as intended.
=> LoadmorebuttoninList - Svelte

libs/sveltekit/src/components/MultiselectList/MultiselectList.stories.ts, libs/sveltekit/src/components/MultiselectList/MultiselectList.svelte
fix(MultiselectList.svelte): Resolve accessibility errors by giving the `list-item` div a role of tab.
- Give the `list-item` div a role of tab and also a key down event to resolve accessibility issues.
fix(MultiselectList.stories.ts): Resolve TypeScript error for MultiselectList.stories.ts args props
- Updated the MultiselectList story file to correctly import the MultiselectList component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, …
=> MultiselectList-svelte

libs/sveltekit/src/components/NotificationBellIcon/NotificationBellIcon.stories.ts
fix(NotificationBellIcon.stories.ts): Resolve TypeScript error for NotificationBellIcon.stories.ts args props
- Updated the NotificationBellIcon story file to correctly import the NotificationBellIcon component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, NotificationBellIcon component can now be used in Storybook without type errors, and the props can be controlled as intended.
=> NotificationBellIcon-svelte

libs/sveltekit/src/components/NumberedList/NumberedList.stories.ts, libs/sveltekit/src/components/NumberedList/NumberedList.svelte
fix(NumberedList.stories.ts): Resolve TypeScript error for NumberedList.stories.ts args props
- Updated the NumberedList story file to correctly import the NumberedList component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, NumberedList component can now be used in Storybook without type errors, and the props can be controlled as intended.
fix(NumberedList.svelte): Resolve accessibility errors by giving the `list-item` div a role of tab.
- …
=> NumberedList-Svelte

libs/sveltekit/src/components/NumberInputWithIncrement/NumberInputWithIncrement.stories.ts, libs/sveltekit/src/components/NumberedList/NumberedList.stories.ts, libs/sveltekit/src/components/NumberedList/NumberedList.svelte
fix(NumberInputWithIncrement.stories.ts): Resolve TypeScript error for NumberInputWithIncrement.stories.ts args props
- Updated the NumberInputWithIncrement story file to correctly import the NumberInputWithIncrement component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, NumberInputWithIncrement component can now be used in Storybook without type errors, and the props can be controlled as intended.
=> NumberWithIncrement-svelte

libs/sveltekit/src/components/Pagination/Pagination.stories.ts
fix(Pagination.stories.ts): Resolve TypeScript error for Pagination.stories.ts args props
- Updated the Pagination story file to correctly import the Pagination component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, Pagination component can now be used in Storybook without type errors, and the props can be controlled as intended.
=> Pagination - Svelte

libs/sveltekit/src/components/PinnedList/PinnedList.stories.ts, libs/sveltekit/src/components/PinnedList/PinnedList.svelte
fix(PinnedList.stories.ts): Resolve TypeScript error for PinnedList.stories.ts args props
- Updated the PinnedList story file to correctly import the PinnedList component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, PinnedList component can now be used in Storybook without type errors, and the props can be controlled as intended.
fix(PinnedList.svelte): Resolve accessibility errors by giving the list-item li a role of tab.
- Give the …
=> PinnedList - Svelte

libs/sveltekit/src/components/StatusDots/StatusDots.stories.ts
fix(StatusDots.stories.ts): Resolve TypeScript error for StatusDots.stories.ts args props
- Updated the StatusDots story file to correctly import the StatusDots component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, StatusDots component can now be used in Storybook without type errors, and the props can be controlled as intended.
=> StatusDots-Svelte

libs/sveltekit/src/components/Stepper/Stepper.stories.ts
fix(Stepper.stories.ts): Resolve TypeScript error for Slider.stories.ts args props
- Updated the Stepper story file to correctly import the Stepper component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
With these updates, Stepper component can now be used in Storybook without type errors, and the props can be controlled as intended.
=> Stepper - Svelte

libs/sveltekit/src/components/Toast/Toast.stories.ts
Refactor Toast stories to use StoryFn for improved template binding
- Updated import from StoryObj to StoryFn in Toast.stories.ts
- Refactored story exports to utilize a template function for cleaner code
- Maintained existing functionality and args for all toast variants (Default, Success, Error, Warning, Info, Dismissed)
=> Toast-Sveltekit

libs/sveltekit/src/components/VirtualizedList/VirtualizedList.stories.ts
Refactor VirtualizedList story: Change control type from `array` to `object` and update Story type to StoryFn
- Update the story import to StoryFn.
=> VirtualizedList - Sveltekit

libs/sveltekit/src/components/VisualCueForAccessibilityFocusIndicator/VisualCueForAccessibilityFocusIndicator.stories.ts, libs/sveltekit/src/components/VisualCueForAccessibilityFocusIndicator/VisualCueForAccessibilityFocusIndicator.svelte
Refactor Storybook stories for VisualCueForAccessibilityFocusIndicator component
- Updated import statements to include StoryFn type.
- Replaced the previous StoryObj definitions with a Template function for better reusability.
- Defined stories for Default, Focused, and Unfocused states using the new Template approach.
This change enhances the structure and maintainability of the Storybook stories.
Fix focus indicator class binding in VisualCueForAccessibilityFocusIndicator component
- Removed redundant tabindex attribute from the focus indicator div.
This change improves the accessibility and functionality of the focus indicator.
=> VisualCueForAccesisibiltyFocusIndicator - Sveltekit

libs/svelte/README.md
Closes - #204
- Updated the title and content to reference Vite and TypeScript explicitly.
- Followed the structure and examples from libs/react/README.md and libs/vue/README.md.
=> docs: align documentation to include Vite and TypeScript references

libs/vue/package-lock.json, libs/vue/package.json, libs/vue/src/shims-vue.d.ts, libs/vue/tsconfig.app.json, libs/vue/tsconfig.node.json, libs/vue/vite.config.ts
Right now, if you try to import any of the components in a Vue project, it won't work because the dist is not being exported. I fixed that by adding the dist folder to the exported files.
I also added typing support by including the declaration file for all the components.
This PR also fixes styling by adding a `./dist/style.css` entry point that can be imported to import all the stylings.
=> fix: vue library
