libs/vue/src/components/BatteryLevelIndicator/BatteryLevelIndicator.vue, libs/vue/src/components/BottomNavigationBar/BottomNavigationBar.vue, libs/vue/src/components/BreadcrumbWithDropdowns/BreadcrumbWithDropdowns.vue, libs/vue/src/components/BrushTool/BrushTool.stories.ts, libs/vue/src/components/CalendarView/CalendarView.stories.ts, libs/vue/src/components/CalendarView/CalendarView.vue, libs/vue/src/components/Canvas/Canvas.stories.ts, libs/vue/src/components/Captcha/Captcha.stories.ts, libs/vue/src/components/Captcha/Captcha.vue
This PR resolves two issues in the Captcha component and its corresponding Storybook file:
Prop Access Issue in Captcha Component:
The solveCaptcha function was not properly accessing the captchaText prop. This was fixed by passing props to the setup function, allowing the solveCaptcha function to correctly reference props.captchaText.
TypeScript Errors in Storybook:
In the Captcha.vue component:
Passed props to the setup function to ensure proper access to the captchaText prop.
Updated the solveCaptcha function to reference props.captchaText correctly.
In the Captcha.stories.ts file: …
=> fix: Resolve TypeScript errors and prop access issue in Captcha component and stories

libs/vue/src/components/BatteryLevelIndicator/BatteryLevelIndicator.vue, libs/vue/src/components/BottomNavigationBar/BottomNavigationBar.vue, libs/vue/src/components/BreadcrumbWithDropdowns/BreadcrumbWithDropdowns.vue, libs/vue/src/components/BrushTool/BrushTool.stories.ts, libs/vue/src/components/CalendarView/CalendarView.stories.ts, libs/vue/src/components/CalendarView/CalendarView.vue, libs/vue/src/components/Canvas/Canvas.stories.ts, libs/vue/src/components/Captcha/Captcha.stories.ts, libs/vue/src/components/Captcha/Captcha.vue, libs/vue/src/components/CardActions/CardActions.stories.ts
=> Fix(CardActions.stories.ts): Resolve the import and type errors in the CardActions stories.

libs/vue/src/components/BatteryLevelIndicator/BatteryLevelIndicator.vue, libs/vue/src/components/BottomNavigationBar/BottomNavigationBar.vue, libs/vue/src/components/BreadcrumbWithDropdowns/BreadcrumbWithDropdowns.vue, libs/vue/src/components/BrushTool/BrushTool.stories.ts, libs/vue/src/components/CalendarView/CalendarView.stories.ts, libs/vue/src/components/CalendarView/CalendarView.vue, libs/vue/src/components/Canvas/Canvas.stories.ts, libs/vue/src/components/Captcha/Captcha.stories.ts, libs/vue/src/components/Captcha/Captcha.vue, libs/vue/src/components/CardActions/CardActions.stories.ts, libs/vue/src/components/CardBadge/CardBadge.stories.ts, libs/vue/src/components/CardBody/CardBody.stories.ts, libs/vue/src/components/CardFooter/CardFooter.stories.ts, libs/vue/src/components/CardHeader/CardHeader.stories.ts, libs/vue/src/components/CardImage/CardImage.stories.ts
=> Fix(CardImage.stories.tsx): Resolve the import and type errors in the CardImage stories.

libs/vue/src/components/ColumnVisibilityToggle/ColumnVisibilityToggle.stories.ts, libs/vue/src/components/ColumnVisibilityToggle/ColumnVisibilityToggle.vue
fix(ColumnVisibilityToggle.stories): add Meta and StoryFn types to Storybook file to resolve TypeScript errors.
fix(ColumnVisibilityToggle.vue): Resolve TypeScript error by removing unused import.
=> Fix(ColumnVisibilityToggle): Fix TypeScript Errors in the StoryBook File and Component File

libs/vue/src/components/DataExportButton/DataExportButton.stories.ts, libs/vue/src/components/DataExportButton/DataExportButton.vue
fix(DataExportButton.stories.ts): Resolve TypeScript type errors by introducing Meta and StoryFn from storybook.
Beta: TypeScript errors in the Captcha.stories.ts file were resolved by introducing Meta and StoryFn types from @storybook/vue3. This ensures that the Storybook configuration follows proper TypeScript conventions.
fix(DataExportButton.vue): Resolve TypeScript unused error: Added a simple log to log the unused `format` variable.
=> Fix(DataExportButton): Resolve TypeScript type and unused erros for the component and storybook files. 

libs/vue/src/components/DealerButton/DealerButton.stories.ts
fix(DealerButton.stories.ts): Refactor DealerButton StoryBook Stories to Correctly Import and Use StoryFn.
=> fix(DealerButton.stories.ts): Refactor DealerButton StoryBook Stories to Correctly Import and Use StoryFn.

libs/vue/src/components/DiscardPile/DiscardPile.stories.ts
- Updated Template to use StoryFn and Meta for better type inference.
=> fix(DiscardPile.stories.ts): Resolve TypeScript type error by adding type definition for args in DiscardPile story.

libs/vue/src/components/EraserTool/EraserTool.stories.ts
- Fixed incorrect import of StoryFn module to ensure proper functionality.
=> fix:(EraserTool.stories.ts) - Fix import error for the StoryFn module.

libs/vue/src/components/EventDetailsDialog/EventDetailsDialog.vue, libs/vue/src/components/EventFilterBar/EventFilterBar.stories.ts
- Remove invalid activeFilters prop from stories
- Add play functions to demonstrate different filter states
- Update story template to remove v-bind arguments
- Add proper argTypes documentation for internal state
- Fix TypeScript errors in story configuration
=> fix(storybook): Update EventFilterBar stories to handle computed properties

libs/vue/src/components/EventReminderSystem/EventReminderSystem.vue
- Add explicit prop definitions for feedbackMessage
- Implement proper prop handling in component setup
=> fix(components): resolve TypeScript prop validation in EventReminderSystem

libs/vue/src/components/FileUpload/FileUpload.stories.ts
-Resolve type errors by introducing Meta and StoryFn modules from storybook for proper type handling.
=> fix(FileUpload.stories.ts): Resolve TypeScript type errors.

libs/vue/src/components/FilterableList/FilterableList.stories.ts
- Added a null check for the input element to prevent potential runtime errors.
- Cast the button element as HTMLElement to safely access the click method.
=> fix(FilterableList.stories.ts): add null checks for input element and cast button as HTMLElement

libs/vue/src/components/GroupedList/GroupedList.stories.ts, libs/vue/src/components/HandOfCards/HandOfCards.stories.ts, libs/vue/src/components/HandOfCards/HandOfCards.vue
fix(HandOfCards.vue): Resolve unused variable error by removing the index variable.
fix(HandOfCards.stories.ts): Resolve TypeScript type errors : - Introduce Meta and StoryFn modules for proper type handling.
=> Fix - HandOfCards

libs/vue/src/components/FlipCard/FlipCard.stories.ts
- Introduce the Meta and StoryFn modules from Storybook for proper type handling.
=> fix(FlipCard.stories.ts): Resolve TypeScript type errors.

libs/vue/src/components/LayerPanel/LayerPanel.stories.ts
- Correct the import module from Story to StoryFn, the correct import module.
=> fix(LayerPanel.stories.ts): Resolve import error:

libs/vue/src/components/MediaGallery/MediaGallery.stories.ts, libs/vue/src/components/MediaGallery/MediaGallery.vue, libs/vue/src/components/MultipleChoicePoll/MultipleChoicePoll.stories.ts, libs/vue/src/components/MultipleChoicePoll/MultipleChoicePoll.vue
- Correct import module for Story to StoryFn.
- Correct the control type for array to object.
- Resolve the unused variable error by removing the prop argument passed as it was not being used.
=> Multiple choice poll

libs/vue/src/components/MediaGallery/MediaGallery.stories.ts, libs/vue/src/components/MediaGallery/MediaGallery.vue
- Passed the props as an argument in setup for the image prop to be accessed.
- Use the correct array control which is object in storybook.
=> Media gallery

libs/vue/src/components/PaginationControl/PaginationControl.stories.ts
-Introduced the Meta and StoryFn modules for proper type handling.
=> fix(PaginationControl.stories.ts): Resolve TypeScript type errors.

libs/vue/src/components/Pot/Pot.stories.ts
- Changed the control type to object from array.
=> fix(Pot.stories.ts): Resolve TypeScript type errors.

libs/vue/src/components/PublicViewCalendar/PublicViewCalendar.stories.ts, libs/vue/src/components/PublicViewCalendar/PublicViewCalendar.vue
- Declared selectedEvent prop in PublicViewCalendar component to allow Storybook to access it.
- Initialized selectedEvent variable in setup function with the prop value.
- Ensured selectedCategoryProp is also accessible for Storybook use.
=> fix: add selectedEvent prop to PublicViewCalendar for Storybook compatibility

libs/vue/src/components/RulerAndGuides/RulerAndGuides.stories.ts, libs/vue/src/components/RulerAndGuides/RulerAndGuides.vue
- Log the index variable to solve the unused variable error.
fix(RulerAndGuides.stories.ts): Resolve incorrect import for the StoryFn module.
=> fix(RulerAndGuides.vue): Resolve the unused variable error:

libs/vue/src/components/RecurringEventScheduler/RecurringEventScheduler.stories.ts, libs/vue/src/components/RecurringEventScheduler/RecurringEventScheduler.vue
- Declared a prop feedbackMessageProp that was passed to the storybook as a prop.
=> fix(RecurringEventScheduler): Resolve feedbackMessage not accesible to story.

libs/vue/src/components/RankingPoll/RankingPoll.stories.ts
- Resolved import error for StoryFn
- Resolved control type error for object
=> fix(RankingPoll.stories.ts): Resolve TypeScript type errors.

libs/vue/src/components/StarRatingPoll/StarRatingPoll.stories.ts, libs/vue/src/components/Stepper/Stepper.stories.ts
fix(Stepper.stories.ts): Resolve control type for steps by replacing it with object.
=> fix(StarRatingPoll.stories.ts): Resolve import error for StoryFn.

libs/vue/src/components/SortControl/SortControl.stories.ts, libs/vue/src/components/SortControl/SortControl.vue, libs/vue/src/components/SortableTable/SortableTable.stories.ts, libs/vue/src/components/SortableTable/SortableTable.vue
fix(SortControl.vue): Resolve unused variabe and incorrect value binding error.
- Remove the computed import as it was not used.
- Correctly bind the aria-disabled attribute to the disabled value.
fix(SortControl.stories.ts): Resolve TypeScript type errors by using StoryFn and Meta modules for proper type handling.
=> Sort control

libs/vue/src/components/SortableTable/SortableTable.stories.ts, libs/vue/src/components/SortableTable/SortableTable.vue
fix(SortableTable.vue):Fix sorting error by ensuring sortKey is not null
Updated the sorting logic in the filteredAndSortedData computed property to use a non-null assertion on sortKey. This prevents TypeScript errors related to using null as an index type, ensuring proper sorting functionality.
fix(SortableTable.stories.ts): Resolve null errors by adding null check and casting to right Element type.
=> Sortable table

libs/vue/src/components/LiveResultsPoll/LiveResultsPoll.stories.ts
- replace null with undefined as it is the value accepted by the initialValue variable.
=> fix(LiveResultsPoll.stories.ts): Resolve TypeScript type error:

libs/vue/src/components/RadioButton/RadioButton.stories.ts, libs/vue/src/components/RadioButton/RadioButton.vue
fix(RadioButton.vue): Correctly bind the checked and disabled values to the aria-checked and aria-disabled attributes.
fix(RadioButton.stories.ts): Resolve TypeScript type errors.
-Introduce StoryFn and Meta modules from storybook for proper error handling.
=> Radio button

libs/vue/src/components/Slider/Slider.vue
- Remove props and ref variables, they are not used.
=> fix(Slider.vue): Resolve unused variables errors.

libs/vue/src/components/ShapeLibrary/ShapeLibrary.stories.ts, libs/vue/src/components/ShapeLibrary/ShapeLibrary.vue
fix(ShapeLibrary.stories.ts): Resolve import error-Resolve the StoryFn import error.
fix(ShapeLibrary.vue): Resolve unused variable by logging shape.
=> Shape library

libs/vue/src/components/SearchBarWithSuggestions/SearchBarWithSuggestions.stories.ts, libs/vue/src/components/SearchBarWithSuggestions/SearchBarWithSuggestions.vue
fix(SearchBarWithSuggestions.stories.ts): Resolve type errors by using Meta and StoryFn for proper error handling.
fix(SearchBarWithSuggestions.vue): Resolve unused variable and return error.
=> Search bar with suggestionsn

libs/vue/src/components/RangeSlider/RangeSlider.stories.ts
-Introduce Meta and StoryFn for proper type handling.
=> fix(RangeSlider.stories.ts): Resolve TypeScript type errors.

libs/vue/src/components/TimelineAdjuster/TimelineAdjuster.vue
- Add the feedbackMessage prop in order for it to be accessed by the storybook file.
=> fix(TimelineAdjuster.vue): Resolve TypeScript type error by passing prop to the component.

libs/vue/src/components/SingleChoicePoll/SingleChoicePoll.stories.ts
- Replace array control with array
- Resolve StoryFn import error/
=> fix(SingleChoicePoll.stories.ts): Resolve TypeScript type error and import error.

README.md
Added installation prerequisites for npm and instructions to initialize Vite applications for Vue, React, and Svelte with TypeScript. Reorganized installation steps for clarity, including commands for installing Swarmakit libraries. Included Documentation Links with descriptions for each library’s documentation. Updated Contributing section to reference CONTRIBUTING.md. Added build status and hits badges for enhanced repository visibility and quick status updates.
=> docs(README.md): update README with installation instructions, setup, and badges

CONTRIBUTING.md
Updated the contribution guidelines to follow the feature-based branching principle. Added detailed steps for forking the repository, cloning, and setting up the development environment. Included instructions for navigating to the desired library and pulling the latest changes. Specified testing procedures using npm run build to check for errors. Provided a clear example commit message format.
Included reminders for keeping branches updated and adhering to the project's code of conduct.
=> feat(CONTRIBUTING.md ): Enhance CONTRIBUTING.md for Swarmakit

libs/sveltekit/README.md
- Instructions for installing the Swarmakit Svelte Library via npm
- Guide on initializing a Vite + Svelte project with TypeScript support
- Sample code for importing and using Swarmakit components within Svelte
- Link to Svelte components folder for convenient reference to available components
=> docs(svelte): Provide detailed usage instructions for Swarmakit Svelte Library

libs/vue/README.md
- Includes npm installation instructions and Vite project setup for Vue 3 with TypeScript
- Step-by-step guide for initializing a Vite + Vue project
- Example code for importing and using components within Vue files
- Link to Vue components folder for easy access to available components
=> docs(vue lib): Add detailed usage guide for Swarmakit Vue Library

libs/react/README.md
- Detailed setup and installation instructions for using Swarmakit React Library in a Vite project
- Guide on initializing a Vite + React TypeScript project
- Example usage of components within a React environment
- Link to components folder for easy reference of available components
=> docs(react-lib): Add comprehensive usage documentation for Swarmakit React Library

libs/vue/package.json
Correctly installed the quill package from npm.
=> fix(RichTextEditor.vue): Resolved quill package import error:

libs/sveltekit/src/components/ExpandableList/ExpandableList.stories.ts, libs/sveltekit/src/components/ExpandableList/ExpandableList.svelte
fix(ExpendableList.svelte): add keyboard event handler to item labe and list-item for accessibility
- Added on:keydown event to the item label div to handle keyboard interactions (Enter and Space keys).
- Included tabindex="0" to make the div focusable for keyboard navigation.
fix(ExpendableList.stories.ts): Resolve TypeScript error for DragAndDropFileArea.stories.ts args props
- Updated the ExpandableList story file to correctly import the ExpendableList component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
- This change addresses the TypeScript error: "Object literal may only specify known properties, and 'isOpen' does not exist in type 'Partial<ComponentAnnotations<...>>'" by ensuring that the props are correctly defined …
=> ExpendableList-SvelteKit

libs/sveltekit/src/components/ExpandableList/ExpandableList.stories.ts, libs/sveltekit/src/components/ExpandableList/ExpandableList.svelte, libs/sveltekit/src/components/FavoritesList/FavoritesList.stories.ts, libs/sveltekit/src/components/FavoritesList/FavoritesList.svelte
fix(ExpendableList.svelte): add keyboard event handler to item labe and list-item for accessibility
- Added on:keydown event to the item label div to handle keyboard interactions (Enter and Space keys).
- Included tabindex="0" to make the div focusable for keyboard navigation.
fix(ExpendableList.stories.ts): Resolve TypeScript error for DragAndDropFileArea.stories.ts args props
- Updated the ExpandableList story file to correctly import the ExpendableList component and define the `argTypes` for the props, allowing Storybook to properly handle the component's properties.
- This change addresses the TypeScript error: "Object literal may only specify known properties, and 'isOpen' does not exist in type 'Partial<ComponentAnnotations<...>>'" by ensuring that the props are correctly defined …
=> FavoritesList-SvelteKit

libs/sveltekit/src/components/TimelineList/TimelineList.stories.ts, libs/sveltekit/src/components/TimelineList/TimelineList.svelte
Refactor TimelineList story: Update Story type and control type for events
- Update the Story type by correctly importing StoryFn.
- Update the control type for events to object instead of array as it's the supported type.
Enhance TimelineList accessibility: Add role attribute to button element
- Added `role='button'` to the clickable element in TimelineList.svelte to improve accessibility for keyboard and screen reader users.
=> TimeLineList  - Sveltekit

libs/sveltekit/src/components/ToggleSwitch/ToggleSwitch.stories.ts, libs/sveltekit/src/components/ToggleSwitch/ToggleSwitch.svelte
Fix toggle behavior in ToggleSwitch component to prevent toggling when disabled
Refactor ToggleSwitch stories to use StoryFn for better type safety and consistency.
=> ToggleSwitch-sveltekit

libs/sveltekit/src/components/TreeviewList/TreeviewList.stories.ts, libs/sveltekit/src/components/TreeviewList/TreeviewList.svelte
Refactor TreeviewList story to use StoryFn type and update control type to object
Update TreeviewList story to set expanded state based on node index
Enhance TreeviewList accessibility and structure by adding ARIA roles and attributes to tree nodes and their contents. Import TreeviewList component for improved modularity.
=> TreeViewList - Sveltekit

libs/sveltekit/src/components/ValidationMessages/ValidationMessages.stories.ts
Refactor: ValidationMessages stories to use StoryFn for better type safety and consistency.
=> ValidationMessages - Sveltekit

libs/sveltekit/src/components/SortableTable/SortableTable.stories.ts, libs/sveltekit/src/components/SortableTable/SortableTable.svelte
Refactor SortableTable component to improve structure and accessibility
- Moved script context to module level for better organization.
- Added missing aria-sort values for improved accessibility.
- Removed redundant role attributes to streamline the markup.
Refactor SortableTable story to use StoryFn type for improved type safety
=> SortableTable - sveltekit
